=== ElenaGavrilovaMMF/java/sax-stax-dom/out/artifacts/SaxStaxDom_war_exploded/data/flower.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.com/flower"
           xmlns:tns="http://www.example.com/flower"
           elementFormDefault="qualified">
    <xs:element name="flowers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="flower"
                            type="tns:flower"
                            minOccurs="1"
                            maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="flower">
        <xs:sequence>
            <xs:element name="name" type="tns:name" />
            <xs:element name="origin">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z]{0,20}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="visual" type="tns:visual" />
            <xs:element name="growing" type="tns:growing" />
            <xs:element name="multiplying">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="sheets"/>
                        <xs:enumeration value="cuttings"/>
                        <xs:enumeration value="seeds"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="date" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="soil" use="optional" default="podzolic">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="podzolic"/>
                    <xs:enumeration value="ground"/>
                    <xs:enumeration value="sod-podzolic"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="name">
        <xs:restriction base="xs:ID">
            <xs:pattern value="([a-zA-Z])[a-zA-Z0-9-]{1,50}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="visual">
        <xs:sequence>
            <xs:element name="stem" type="xs:string" />
            <xs:element name="sheet" type="xs:string" />
            <xs:element name="size" type="xs:positiveInteger" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="growing">
        <xs:sequence>
            <xs:element name="temperature" type="xs:positiveInteger" />
            <xs:element name="lighting" type="xs:boolean" />
            <xs:element name="irrigation" type="xs:positiveInteger" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ElenaGavrilovaMMF/java/sax-stax-dom/out/artifacts/SaxStaxDom_war_exploded/data/flower.xml
<?xml version="1.0" encoding="UTF-8" ?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.com/flower"
         xsi:noNamespaceSchemaLocation="flower.xsd">
    <flower soil="podzolic">
        <name>Azalea</name>
        <origin>Bel</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>sheets</multiplying>
        <date>2018-09-01</date>
    </flower>
    <flower soil="podzolic">
        <name>Aloe</name>
        <origin>Bel</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>sheets</multiplying>
        <date>2017-12-10</date>
    </flower>
    <flower soil="podzolic">
        <name>Pansies</name>
        <origin>Ru</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>sheets</multiplying>
        <date>2017-10-02</date>
    </flower>
    <flower soil="podzolic">
        <name>Aster</name>
        <origin>Ru</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>sheets</multiplying>
        <date>2018-09-01</date>
    </flower>
    <flower soil="podzolic">
        <name>Begonia</name>
        <origin>En</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>sheets</multiplying>
        <date>2018-10-01</date>
    </flower>
    <flower soil="podzolic">
        <name>Cornflower</name>
        <origin>En</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>sheets</multiplying>
        <date>2018-10-01</date>
    </flower>
    <flower soil="ground">
        <name>Verbena</name>
        <origin>En</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>cuttings</multiplying>
        <date>2017-11-12</date>
    </flower>
    <flower soil="ground">
        <name>Carnation</name>
        <origin>Fr</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>cuttings</multiplying>
        <date>2017-11-12</date>
    </flower>
    <flower soil="ground">
        <name>Dahlia</name>
        <origin>Fr</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>cuttings</multiplying>
        <date>2017-11-12</date>
    </flower>
    <flower soil="ground">
        <name>Geranium</name>
        <origin>Bel</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>cuttings</multiplying>
        <date>2018-06-12</date>
    </flower>
    <flower soil="ground">
        <name>Herbera</name>
        <origin>Yulia</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>seeds</multiplying>
        <date>2018-06-12</date>
    </flower>
    <flower soil="sod-podzolic">
        <name>Glcinia</name>
        <origin>Bel</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>seeds</multiplying>
        <date>2018-06-12</date>
    </flower>
    <flower soil="sod-podzolic">
        <name>Cow-Wheat</name>
        <origin>Ru</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>seeds</multiplying>
        <date>2018-05-10</date>
    </flower>
    <flower soil="sod-podzolic">
        <name>WillowHerb</name>
        <origin>Ru</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>seeds</multiplying>
        <date>2018-05-10</date>
    </flower>
    <flower soil="sod-podzolic">
        <name>Iris</name>
        <origin>En</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>seeds</multiplying>
        <date>2018-05-11</date>
    </flower>
    <flower soil="sod-podzolic">
        <name>Cannee</name>
        <origin>En</origin>
        <visual>
            <stem>red</stem>
            <sheet>green</sheet>
            <size>20</size>
        </visual>
        <growing>
            <temperature>10</temperature>
            <lighting>true</lighting>
            <irrigation>30</irrigation>
        </growing>
        <multiplying>seeds</multiplying>
        <date>2018-05-11</date>
    </flower>
</flowers>
